# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: docker/login-action@v4
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - uses: docker/build-push-action@v7
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
on:
  release:
    types:
      - created
permissions:
  contents: read
  packages: write
